declare const nodeModule : NodeModule;
declare var authServ : any;
declare var utilisateurService : any;
declare var horServ : any;
declare var utilSocket : any;
declare var socketService : any;
declare var serv : any;
declare var prefServ : any;
declare var serviceService : any;
declare var prefEmp: any;
declare var rendServ : any;
declare var chiffServ : any;